version: '3'
services:
  swarm-monitor:
    image: withinboredom/dapr-swarm-monitor:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    network_mode: none
    deploy:
      placement:
        constraints:
          - "node.role==manager"
      replicas: 1
  swarm-injector:
    image: withinboredom/dapr-swarm-injector:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    network_mode: none
    deploy:
      mode: global
      labels:
        swarm.inject: "true"
